# Generated by Django 2.1.1 on 2018-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('application_id', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
